baseurl = "https://gergelybrautigam.com" # Hostname (and path) to the root.
title = "Gergely Brautigam" # Site title.
theme = "coder-portfolio" # Set the theme.
languagecode = "en" # The site’s language code used to generate RSS.
defaultcontentlanguage = "en" # The default content language.

paginate = 20 # Default number of pages per page in pagination.

pygmentsstyle = "b2" # Color-theme or style for syntax highlighting.
pygmentscodefences = true # Enable code fence background highlighting.
pygmentscodefencesguesssyntax = true # Enable syntax guessing for code fences without specified language.
pygmentsUseClasses = true # new add

disqusShortname = "hannibalDisqus" # Enable or disable Disqus.

[params] # theme parameters
    author = "Gergely Brautigam" # Author's name.
    info = "Cloud Engineer Gopher Adventurer" # Author's job title or info.
    description = "Gergely Brautigam's lair" # Site description.
    avatarurl = "images/avatar.jpg" # Contain the path of the optionnal avatar in the static folder.

    footercontent = "I am all." # Add footer content
    fixedbarContent = "Click for a surprise" # Add fixedbar content
    fixedbarContentAfter = "SURPRISE" # Add fixedbar content after click

    # Whether you want to hide copyright and credits in the footer.
    hideCredits = false
    hideCopyright = true

    # Custom CSS
    custom_css = []

    # Alignment of Mobile Menu items
    itemscentered = true

    # RTL support
    rtl = false

    snsShare = true # new add

    thumbnail = "images/tn.png" # default sns thumbnail

    # Multilanguage mode
    langseparator = "|" # Separates menus from language selectors when site is multilingual.

# Social links
[[params.social]]
    name = "Github"
    weight = 1
    url = "https://github.com/Skarlso/"
[[params.social]]
    name = "Blog"
    weight = 2
    url = "https://skarlso.github.io"

# Menu links
[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "posts"
[[menu.main]]
    name = "About"
    weight = 2
    url = "about"
